image: registry.hypriot.com/hypriot/dockerindocker
docker:
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
git:
  path: github.com/hypriot/dockerfiles
script:
  - echo "+++++ start docker daemon +++++"
  - wrapdocker &
  - sleep 5
  - docker login --username=$$REGISTRY_USER --password=$$REGISTRY_PASSWORD --email=$$REGISTRY_USER_EMAIL $$REGISTRY_URL
  - echo "+++++ build docker image +++++"
  - cd $(git log --oneline --name-status -1 | grep "M\|A" | dirname `awk -F " " '{print $2}'`| grep -v "\.")
  - make imagename=$(git log --oneline --name-status -1 | grep "M\|A" | dirname `awk -F " " '{print $2}'`| grep -v "\.") build
  - echo "+++++ stop docker daemon +++++"
  - start-stop-daemon --stop --pidfile "/var/run/docker.pid"
  - echo "#####################\n***** COMPLETED *****\n#####################"
notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    on_started: false
    on_success: true
    on_failure: true
